"""
report.py
Generates structured benchmark reports in JSON and Markdown format.

The markdown report is designed to be readable as a GitHub README
or pasted directly into a portfolio page.
"""

import json
import os
from datetime import datetime


def generate_report(results: dict, output_dir: str = "./results"):
    """
    Args:
        results: dict mapping detector_name → {metrics, worst_cases, total_samples}
        output_dir: where to write the report files
    """
    os.makedirs(output_dir, exist_ok=True)
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # ── JSON report (machine-readable) ────────────────────────────────────────
    json_report = {
        "generated_at": timestamp,
        "dataset":      "CelebDF",
        "detectors":    results,
    }
    json_path = os.path.join(output_dir, "benchmark_report.json")
    with open(json_path, "w") as f:
        json.dump(json_report, f, indent=2)

    # ── Markdown report (human-readable) ──────────────────────────────────────
    md = _build_markdown(results, timestamp)
    md_path = os.path.join(output_dir, "benchmark_report.md")
    with open(md_path, "w") as f:
        f.write(md)

    # ── Console summary ────────────────────────────────────────────────────────
    _print_summary_table(results)


def _build_markdown(results: dict, timestamp: str) -> str:
    lines = [
        "# Deepfake Detection Benchmark Report",
        f"**Dataset:** CelebDF  |  **Generated:** {timestamp}",
        "",
        "---",
        "",
        "## Results Summary",
        "",
    ]

    # Main comparison table
    headers = ["Detector", "Accuracy", "Precision", "Recall", "F1", "AUC-ROC", "FPR", "FNR", "Samples"]
    lines.append("| " + " | ".join(headers) + " |")
    lines.append("| " + " | ".join(["---"] * len(headers)) + " |")

    for det_name, data in results.items():
        m = data["metrics"]
        short_name = det_name.split("(")[0].strip()  # remove parenthetical
        row = [
            short_name,
            f"{m['accuracy']:.4f}",
            f"{m['precision']:.4f}",
            f"{m['recall']:.4f}",
            f"{m['f1']:.4f}",
            f"{m['auc_roc']:.4f}",
            f"{m['false_positive_rate']:.4f}",
            f"{m['false_negative_rate']:.4f}",
            str(data["total_samples"]),
        ]
        lines.append("| " + " | ".join(row) + " |")

    lines += ["", "---", "", "## Detector Details", ""]

    for det_name, data in results.items():
        m = data["metrics"]
        lines += [
            f"### {det_name}",
            "",
            "**Confusion Matrix:**",
            "",
            "| | Predicted Real | Predicted Fake |",
            "| --- | --- | --- |",
            f"| **Actual Real** | {m['true_negatives']} (TN) | {m['false_positives']} (FP) |",
            f"| **Actual Fake** | {m['false_negatives']} (FN) | {m['true_positives']} (TP) |",
            "",
        ]

        # Worst cases analysis
        wc = data.get("worst_cases", {})
        if wc.get("worst_false_positives"):
            lines.append("**Worst False Positives** (real images classified as fake):")
            lines.append("")
            for p in wc["worst_false_positives"][:3]:
                fname = os.path.basename(p["path"])
                lines.append(f"- `{fname}` — confidence: {p['confidence']:.4f}")
            lines.append("")

        if wc.get("worst_false_negatives"):
            lines.append("**Worst False Negatives** (deepfakes that slipped through):")
            lines.append("")
            for p in wc["worst_false_negatives"][:3]:
                fname = os.path.basename(p["path"])
                lines.append(f"- `{fname}` — confidence: {p['confidence']:.4f}")
            lines.append("")

    # Best detector summary
    if len(results) > 1:
        best = max(results.items(), key=lambda x: x[1]["metrics"]["auc_roc"])
        lines += [
            "---",
            "",
            "## Conclusion",
            "",
            f"**Best detector by AUC-ROC:** `{best[0]}` with AUC={best[1]['metrics']['auc_roc']:.4f}",
            "",
            "The frequency-domain baseline provides an interpretable lower bound — it requires no "
            "training and exploits known artifacts from GAN upsampling. The fine-tuned EfficientNet "
            "learns richer spatial features (blending boundaries, skin texture inconsistencies) that "
            "the FFT approach cannot capture, explaining the performance gap.",
            "",
        ]

    lines += [
        "---",
        "",
        "*Generated by Deepfake Detection Benchmark Suite — Clark University Research*",
    ]

    return "\n".join(lines)


def _print_summary_table(results: dict):
    """Prints a clean ASCII summary table to stdout."""
    col_w = 28

    print("\n" + "=" * 75)
    print("  BENCHMARK RESULTS")
    print("=" * 75)
    print(f"  {'Detector':<{col_w}}  {'Accuracy':>9}  {'Precision':>9}  {'Recall':>7}  {'F1':>7}  {'AUC':>7}")
    print("  " + "-" * 71)

    for det_name, data in results.items():
        m = data["metrics"]
        short = det_name[:col_w]
        print(f"  {short:<{col_w}}  "
              f"{m['accuracy']:>9.4f}  "
              f"{m['precision']:>9.4f}  "
              f"{m['recall']:>7.4f}  "
              f"{m['f1']:>7.4f}  "
              f"{m['auc_roc']:>7.4f}")

    print("=" * 75 + "\n")